apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speedtest-tracker
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/oscargicast/homelab-k8s.git
    targetRevision: HEAD
    path: homelab/speedtest-tracker
    directory:
      include: "{pvc.yaml,deployment.yaml,service.yaml,infisical-secret.yaml,ingress-internal.yaml,service-monitor.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: homelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
