apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-tracker-data
  namespace: homelab
  labels:
    app.kubernetes.io/name: speedtest-tracker
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
