---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: speedtest-tracker-secrets
  namespace: homelab
spec:
  encryptedData:
    APP_KEY: AgCigrQ8kzfGDj52hpXy2KCZKEoirlsvYWN9QyQz88mvbvp2L5QdcSJ3E58Cx/mn5UcSGU9Rjk1x0LO1J2f0PL/fczXTz7XAG6Ee7ABzHH9ssGYWt+90hhBsfNEY+2JM6SOFKJOi7jfGot6yfkV68rDAdDVTC7zOEioTIENdPDY5vW89x1/IJdZkEl4XLrIkE7hUrjyYlodTOHIhHBNX7aP2XzYXhDitanMrkD2iaj20UMBlP9pyrP8GItS+HVCo22qr9esh+gJRVJMUbDJvUtHDF2Pbf8k74JKb8ltvUR5hx+g77ckC7WNPum4OklQZknSDVi/MRZgaDbWvyeaOrvAeHiqxVtKhkIEIuqqQTjchqE7s9Q4Q8jyixPjHjPq87l7/09Yu1OkrecnzZFV262l5ejO53bOEnZVNRmCZnDSOO9xy0AKmdIMFN170FhPCuFm+UcngreTTGYHED5mbpXBrR10HnXMM9za7XZDwx4XXHm38hBlSyohpw60TfIhWpdpY8vMW/q0MP/KRpcd+OhODl2Lgzox+YrQ8BFiAhlq3RfUJ0RS3m77CpirHqv0tRXyF0ZGyIyaIOrwmWmt1fyLNRdhKWC8Kj2NtV8Yf8FhjNt2WgNhIAI5UEJkaguRcV+6vVA/CDwF7q+cRPEaSc80qSVrEeIvvo/sCUGX9YK6uiyDg5+j05/ukDvQDHNiIt8Pfkx3Iroy8AccgtrdtLYWxG3HJJULcg43N0VZ0xndeQr1lZfhLWjfwmRRYf/WkMAX3JGo=
    PROMETHEUS_API_KEY: AgDNYgbebCO0azSGKWuN5qq1t/mQrBW2TkzcXoJyLVTPUzZZ7cntbf/sC0dca1PwDGoUe/26El4FWgePEkQPoPeY376JLaQKtXTWUc79Stwg/V0diIc9iGzz3a84M5aklcq1bp5fzVyG682wrpw2+rYnvnlTy0LFc4nUSCoiY0eGW71g5FH1PjWnviw7S8o9v3zWoR0JNbkcJ1zf0ax1irdCKfj8RSwqp/4uXRUzIjTfKZZ85HgcvXhE2xxHYZzNMYMg8yz/SX4kVGUYyiY+00TW9otOkLCdH3xgzCP7nkFL51AxQ7F7VJBuQF3g6deVmFH57wKC2WxkdLbne+CdpwQScGufu4m0I/1ayCRJHM0SRxwe3PaTw3ArFbR3sSe0v7bIN3JVwA1IFqtFWO3G7jbiyLLgG2GSnoFD0Sls2kZXRAt5UWeWCxLvY5jm7NCrGWWm/E8kdwFTFgQjurk2efdF/cn44fuoC9ATIaNJxX+nBulAkap+/1ckNs2BECnGrijuHcy9wpCPpsgseRMT5mT0WkrHjb3a/8XYgGVu8nJak8vQsyq7S97uP5F5UgybkbJFI4MSh683TNJbhoSyfB2ZPnens4ZzYkD279TZBRNWIE1E8Rio+CyGdCX88cDcPuQ9kibN0GC3j74r/9XaVfWdG/tq26EswCfL2j+GHTk++8XiSu3ciftaX9y2WT/hyK+eUndV2dl62O8gUJ7GouvIroCdXu9+q0nNXF1ISYGO/79ggj3aVD2UzZj5qH5eeicEKPP5iY2lRTsMkNXeAyJo
  template:
    metadata:
      name: speedtest-tracker-secrets
      namespace: homelab
    type: Opaque
