apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-lab
  namespace: databases
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: local-path
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: postgres-lab-app-user
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  monitoring:
    enablePodMonitor: true
