---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-lab-app-user
  namespace: databases
spec:
  encryptedData:
    password: AgA67jfckYnzosNxbe1h6pSP3dPoaV1rGhh06R8gb4L41DMQINYB6ssoxmSNNSsTW4Cwl3t+G8Uhfe2f8GDZsDYD1s1yKKZpQP7WCx0Xyr5r5WSboQmcjObHmRRrYm2ERGJf3WHbTUlFexR7nVQRhZsEoxr7loLvUDk4s89jELbMkZOw8L3znKrG7NCZ3+HE5683HClNB3f3KqemY56xR1kIRffibgqROZtyoDRi7KUw5TzAWUpHsTtQ2m5c8G//3+HcGtghI/N3AQY0iTJbNgn2qbX+zNE0loJrgheL+WfzHOvmu7jOaX6Al+5mwo6tO/l7DmTnUxifFTJckdDBFJjLHzKyfgjWxoVMStIFJZCY7zBO1E8s4TQi1mkGf/BhP359y/2sY66H1g/TwloK/sU/xVmapFEtcBZJUrS7a8HHE0yOehg7X8JuDt4F2SxPlZW48urZPbALUeYg4aEOZ3m5WDIqCVgogx/iavsWNy2jSlsgXVbl2wnGWbB6VHYNYbtj7LUCpjV3OtUn5Id8POsU1iDILSmltrxYf+PPPQXdxvQkZRZ+Sh5QEX60hxuSVQFBk2fsSXj/Og71jOhQqMQEbHiPicfI1n5nQDvNmYYK9uK6e6FK1CyMBU2N5xE9LW4fa22px7D2IcJfpAd2UFuII2gfWSeViLvp6cThZ14bJeDDZ+yrhHXTEgxrdiJOQEizy7+KrQHGq2HalIZtidJRIMRUmojFgxHfK/TZmQ==
    username: AgBFHcwtan8dr42ocYnvEPpewAi440AKQqUGRgZipOykMfIXLp91rKkVUHFXVBvvnt/DZE44pkZN7v+IlPiokVqMINPS+gxAYyvzLaKe52oZDLXhqgbddo699bpe/rx7VXixB9X8m22gj8h5uSjmPhtuloDFe2xgjGay0JGYlzOBNAlgisXvfPOn+fqM9NaRxQ+QE5UU+dLKoHkB6t20KyGINRhJX4NVCSzLIjk4p0PNEVXTOfNTKmFFMxEKMhWDwzUKzc0mEqzwrLHA2g/NUui+T7B4WhvcYP1jXGLZYYSBrc5qpalYxBPeIIqBd7cENvdj4agyKTuqlZvNJjQMCleinH0yHYoDGhGadSflOgU/f1oHTN5K5x/LOekZ20Gi18ZWkk6Qusl62Pnk3mYGsiVkVhKRDD5TkGEgIxyV/bevtX0XyOFmbaF6LhHsT27A3LpaZ8nrWXb3o42aVsFmazTfdEBpy2WK5h89UsX3yD56D+tNaxHCu9EPFSb7+4BJ8iFmtCXzp/9wqxaHAxCwqT/vOZbc0pfWbm6y5RuKMh18cZ6JDpnx+xBdAS9LgZy8N55LUoCQWohH8RqSNdx/bOh3IrxOIcKpqD6EgHEXEvM6kSIg+eHN2xH78BlFFTfMo1T5PoryWPh0XrlR7e7/noTzqbP/k3riF3CWjdvFoy0RSJIBetZkWCTZCVQRFwdlTTQQrVo=
  template:
    metadata:
      name: postgres-lab-app-user
      namespace: databases
    type: kubernetes.io/basic-auth
