apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "65.*"
      helm:
        valueFiles:
          - $values/observability/prometheus/values.yaml
    - repoURL: https://github.com/oscargicast/homelab-k8s.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/oscargicast/homelab-k8s.git
      targetRevision: HEAD
      path: observability/prometheus
      directory:
        include: "{grafana-ingress.yaml,prometheus-ingress.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
