grafana:
  enabled: true
  adminPassword: grafana-admin-CHANGE-ME
  persistence:
    enabled: true
    storageClassName: local-path
    size: 2Gi
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 300Mi
      cpu: 200m
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - oscar-mini-m1.tail90f0a7.ts.net
    path: /grafana
    pathType: Prefix
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana"
      serve_from_sub_path: true

prometheus:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - oscar-mini-m1.tail90f0a7.ts.net
    paths:
      - /prometheus
    pathType: Prefix
  prometheusSpec:
    externalUrl: "http://oscar-mini-m1.tail90f0a7.ts.net/prometheus"
    routePrefix: /prometheus
    retention: 3d
    retentionSize: "8GB"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: 500m

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        memory: 64Mi
        cpu: 10m
      limits:
        memory: 128Mi
        cpu: 100m

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
