apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: "40.0.0"
    helm:
      values: |
        service:
          type: ClusterIP

        ingressClass:
          enabled: true
          isDefaultClass: true

        deployment:
          replicas: 1

        resources:
          requests:
            memory: 64Mi
            cpu: 10m
          limits:
            memory: 128Mi
            cpu: 100m

        ports:
          web: {}
          metrics:
            expose:
              default: true

        metrics:
          prometheus:
            entryPoint: metrics
            addEntryPointsLabels: true
            addRoutersLabels: true
            addServicesLabels: true
            serviceMonitor:
              enabled: true
              namespace: observability
              interval: 30s
              namespaceSelector:
                any: true

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
