apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: n8n-db-user
  namespace: databases
spec:
  resyncInterval: 60
  authentication:
    kubernetesAuth:
      identityId: eb8dcdde-9d20-49e5-a2ff-28e7598bee36
      serviceAccountRef:
        name: infisical-operator-controller-manager
        namespace: infisical-operator
      secretsScope:
        projectSlug: homelab-k8s
        envSlug: prod
        secretsPath: /databases/n8n-postgres
  managedSecretReference:
    secretName: n8n-db-user
    secretNamespace: databases
    creationPolicy: Owner
    secretType: kubernetes.io/basic-auth
