---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-db-user
  namespace: databases
spec:
  encryptedData:
    password: AgBd48SPCE+mzHhfIW5tSWVp/2xzhY0rADTg/P5sRHn/Di8jlOmQuePRyni1r0KChRgTcyPnG4HVHwwMmJWguxyaNB3dmNBOhxZXzvA85WY9J93+1otrlHHcBVGgdsZ4rfrjmQx3JWKvN/TH43AingSSusEt/SpEDCfPcyarZOl36zzlYUQFairg42Jc+KTuUiRawZO8YQ4eDyFgpZVc3B2NAojjOsOcXYIGh1sZlTkJ+8kXqlrwccxvssjPY6gBNDvZ5Gem9S5+/+3pzDaW2mWYSNrNhdZPGpicexz76TYReIupcC7OYF/nfyUs97h6aVmSVd9pQtG0PzOjzmKsnpqdChHZ44te87RtxykthKUQGKgbJdorg/n74vGWXBKHpLj4Vq3pJQUB3X9s3cs6NV2DK/l7FbKKOsiN2QOEKoE8aqg9RpDvnNcCeWJvUz9CRiKDEvvWzOh7KAcHgXWiDyn0491jjazUq5WpnzbZqD3Ma2AOWWHd9iyhaBBzMw1dlxL9vuLd1rBsELeflaBzaAMI6F+eORIivSH7qVruWCjpnzbBa+2U86ZF3XGptGcg/0JJfMhgRNRfzsiEAjiMfxWaJ4z0mqEDvM+fdBB6LCY48/GjMHejfsdoCEq+qTx70FpH1X1K+xKFygFf039G0YUCFvFijrtTmf+5Upu0OmGn217sfPfMqiEZNcfnNaWwgdV4BU/uqEN0pYSp47u1+IHUHrO17QOW7Dv1vgRi2g==
    username: AgAdHFpv/Gx6r+w+PCxxIUF82oGv2tiZMqucWcp/E/G2Afhsqwc+U+T805u+SnHMcHY3/Zn+Ium6d5exT2qgQDUk76FGi35grr0IZ9xKtxCtGf/aExAfY0m3LpebyADObt4aROdHnvojSLs8H2wysc+cGjxIR4M9FeAlS3fZmtlqdR81Zt7r5QaO8xzrc0Y7lKn6cVcScfseKaP8JYIAF1jdW6hWgih5v9W3bP5Z9zIin1o3jurX2ctTilWGLJWotONqDysMY86idpNYhWNBrsHiPBtNgvNroat0X7i62qVDrrToEX9c6FUBf+lw6zHs/0Tc7WLcJkgZSQTIfw9FN5MJcSPPavEx19iCdpEIUfN/aELW3WvuUSxXQB3HeXdcsNX/ZtYf764nA9QsSg8DDaPFpIharOQjo2bhR40GHJ7nVCmRhP4XCxf4fUkEX4sEVEmQUJHaWk1Ao3R0VGCMgyqCFutm95ycmWCye20bwDDhZl/k/vl0b5cwoQyDU8K99h2vQpgAu79CAoOk39i0BQ5j9LG0Y0Ij8UYgzNzwkdgsc3r0DkB6+GPrqp+L+TOx+V2UAx+WtkzfXChSoADx1ULOMNSvhSKI7NAoWA1CzcTLgGbfxSmDuEU8qCrmZ5VUDT4XeUPpaKarWddS0EQG73MaLVFAP3fzMI/j8FD/GdJkcj0EbO3SckF2cVQeV2lgbF1ZPMs=
  template:
    metadata:
      name: n8n-db-user
      namespace: databases
    type: kubernetes.io/basic-auth
