apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/oscargicast/homelab-k8s.git
    targetRevision: HEAD
    path: infrastructure/redis
    directory:
      include: "{deployment.yaml,service.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
