---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCnXPBjGWuH3LAUBuIuJj+T3jUejZboeioE/A2656RE3tndyKyhM66E1HX8RR9HtTlqpsrYjBbu0XXIQNRp3v2RJf81H4WX9h52HSmOcBxQyxtlDmWj1toorWMYHabpCKljeBobufvoiIAhH/Zt4Jk0U0SuOdGNmldI81pPZYX2VM/LAJzFVDkJmYqCf3iLnnMdHvWz4RcZMoMUPRfNGrxAQ69woH/pS+Wngqad1N+gMLz7hCIo7GHd9/WqbHXHEsFrq973pkD+o06z+iBYuijK60whz/vrCRQnNkxwCULnHcjeqcR6kyDk52fkrAZZnXphTryQigmS115m6VBkuA1q7YN2FkR/4SHnC+j81+fDuJ1vTIfFMeJhMq0AL3p5II8JE9W+6N/zaQMTOrcZmnTxAH1zOruX8tQY62C08O7xRVBr2Cx5uVwuJZS54mYFdYzBXjzpH1iLf3De+Lh5e5xX3e6vn5lkn7FuSkvbET2b97yda/JwE1KShJkkifwlVw9C1OURiKOC13W7rFauAMKm+IFOwdfqO2nR7WW4LbVYFpjA2U9odXyLdmSHAH/zvyVvZAdpSLQCplHK92ZXgqYpBaeHIqbRz3oIdT5nMBLQ41Dc5Wf9s3eM6A5pdcENuaEZyyziUHhbYn7Ppu1uqweAoNZSbrM5OzP1i9PEH9HjaL+lPvSnhc80601pehEUA3z9xk+iKQgX82WpWX2lRYqyi4kuTp9MIWn7ngxbDIu8GlPNE6dfYIaycJpqOtUjbCb+LFvWhUVag1UEZlN9O+dpS6c2SOWNx8sf2IY/TID8R8nO0/WOQrS3Pgvz1/KT68QabtKkEQESxySAMEx14Rhlk0djDkHaFCAUYdYoObIUuckhAwWKx0B+OwH4zD4f3m7KQDWo28ydiFLDrp069na+e+dWbM33F1rJ/Y80P45NDmzg/pxSV8R4qTsw0/EBPg+i9LxFxhkcDwm0iv5odOXBD9zj308TaZFILcl2xL1iVQ87iBxIsCBG8LxeuqawLmtVhOdQu0PdnQ==
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared
