apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: oci://8gears.container-registry.com/library/n8n
      chart: n8n
      targetRevision: "2.0.1"
      helm:
        valueFiles:
          - $values/automation/n8n/values.yaml
    - repoURL: https://github.com/oscargicast/homelab-k8s.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/oscargicast/homelab-k8s.git
      targetRevision: HEAD
      path: automation/n8n
      directory:
        include: "{sealed-secret.yaml,infisical-secret.yaml,ingress-public.yaml,service-monitor.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: automation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
