---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-db-credentials
  namespace: automation
spec:
  encryptedData:
    password: AgAB3f1CLnl5ovg2pYsQ0pWWR7/K/cibx2aMtMN3XieCUg0pGGMjdWhxfT5PMwfMqLRgv+4NRgxGmdK2mRxm78JpsLCnjaQmp39pMizJvBf2coNeQDPaQSwa8Xghmdupt8lgAWthsVotqcJny9NlTP/Cu2ZTvzTF0RcVUrDNCpiUuNJiAxFBX3j9XEFc8tS6OqUuodrPmleSdJkqcHt+MovWsvhhZX4mwXH4xAX2ZWV9bdUl00hB/bknMsemwc2kINA34N3TYDqeB2UqOawwGDwyRNGw28Plk+p4xBseZpepViiNmAQlG2wd7JNidFLnHSGHvjAabxwv34siEwVXb37jKVBVvkI+imXdT5517+mWRKSmuVoeo6IPFdkRtUwDyQHEdMMxbhyGj0h2+5o9hzdJv06zyiVrhsGy6m0uE4VFIc4cIm0pse13QtH0Y2VFqgTodY75j0ERSZ8cOQV1hBLImxzUGzEXNB7hy0olFzgW9qT6VNGUE752A3zKEoaYFtA1EV2fRDNBGADh+HfMaw+VCKfhP0/OTBA5Tb7tbrpRCp6OgwBpEWu9RdkpJlaaRNqaQPi2xvTdQkBeiK0+sj6k4jzl2RpxxShVWsg7B7YuAmfainpid+WCnHOv/pT7ZjeTZIjc3HsQr+o8BxR//eYHGaWxcHMMOeNDt5Bf6rYjszFXLypvGrKNLOgTdYiBwZ5qH/0iJXKjztQO4oZDVUPKxfyAcKv6zahUdGGz5g==
  template:
    metadata:
      name: n8n-db-credentials
      namespace: automation
    type: Opaque
