---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-db-credentials
  namespace: automation
spec:
  encryptedData:
    password: AgAQqk9R8bHfmHd+rn9rK1KutTkYHfRc0xI9Mbk9U8RTxwTyzHz6ONBjLzWpCWhu9gYjSpFYawY980fZdLbWjsvmpz+ctXJwLWM8RtcbdaBF6tpN/C8vjwYB4XcWEbuaxYidh8K7QabrFW8cC0sxrvx/T49xREtl9XNmLXKcgBqQijd3GldezFD66dgSA3Wf5MXu91TPxhy/VuX9RF5xUwXDMzDKsrdRnj/nJq6JzeBvJ3ZNCCuJzV5qv3XXwletRxg20iVI8NpS2TO3ynYWr+DNHHAdfZv8Um4m81VOGTKLtous1NUiJU11+NiesCi6IRyIerZAqWVjd32nr8BmiZidcYgQxq0Ey1urvn7ZEWRYZya/vxUFmCvHTT8HUxzUQC3czRMiUSY27GicFF5TQBTPay8KAG3hx7tnRuTd39QTZR465BHsB6S1v1dCv/B4MTrwb5m1HA2eRsfYQ96OpbXagIKsfZ3KhhQSNFAP0XWx/Idf2wRHfVUKY6CGQ8pu10AOBdglOWuQDxVRBqsCDrgR98g8WnUA1vT5D0BlHccG7favG581v4uFsAXaFOhjz3CMtmJDgM/+8Wbbmu4vO7WsiMNIuqgX9Fma7ClFzJ+vCN3RFPqidRSuLWhjlxke9oP0b6cKC02UojN2x6Noc3S+HxScxbc0PUN6wiNi5M2ADHc+5DzbIsJn86TykhzJqQuZ0s817grEVVwhR/EmVJuv/+dcwhcAuPKHQokWjQ==
  template:
    metadata:
      name: n8n-db-credentials
      namespace: automation
    type: Opaque
