---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-db-credentials
  namespace: automation
spec:
  encryptedData:
    password: AgAiGq8DghIIma43GKGiHTr5amydkZBuMZH053qFHOK2wYrt6CH2kejgQWP/aTx7XnvLTLJ/0DC7VX8ck8UEEzgALs+i0QIr+H6DWJPj+3y3xF6TD/5xuQOLqDV7UUhBv04DxWrhXyi3ysRGtYON+wPDSF3YP9jn3U24BI7r73QKiczwHA43gQqzVZSUU40OUcj8AzZaBLuro4/Wsbh0E/bWpHEB5GRxqLQLvrsqee+4JdzJN6fcJw0Gwnlwci6dLuIW4gC00hbyy3Zdla53Ly9u36DF5raXHYNfX53CS3YsMdazzhx6dT05cM6kyUt1CKIh3rXbLTObMlbJQme3N1rcyWpSkQF8tAWNOrIQbRTqTI6qvKJZrf4FTe0/T2qRnAgS6MjF2Sg8wIX88Lms7zlaQb6qTpZPJYnRxz8KP+NSm+MmLtGnII/XYHdBKsOsI7zv3Msd4SFznt7t6bIFJCoaEXm4f5JNuaZuwoFfEixdO/wlxklVJZK6fUFX0sFJxeUtpCsjo4jznMGxGMRAa5gRgx71i5I//2m8kGwcw567XeGJWubAb48cNW/HwELHTDOTfRpBmh5y9In3M79YvXL4xS7M+DDJGIk2vD9dAikMXHW+hrx88JMeCRlWfPbpVxFc6pEhZgGjkw87y3xiMgqSVyMygKB73Oo2LX9BnUhDGn+UDkHYOhhcnjN40Oyn5jHIN+J6Jb9g1+divk6WtGATr5jBV2Al6eysGsuYSA==
  template:
    metadata:
      name: n8n-db-credentials
      namespace: automation
    type: Opaque
