image:
  tag: "2.19.5"

main:
  config:
    db:
      type: postgresdb
      postgresdb:
        host: "n8n-postgres-rw.databases.svc.cluster.local"
        port: 5432
        database: n8n
        user: n8n
        schema: public

  extraEnv:
    N8N_HOST:
      value: "n8n.oscargicast.com"
    N8N_PROTOCOL:
      value: "https"
    N8N_SECURE_COOKIE:
      value: "true"
    WEBHOOK_URL:
      value: "https://n8n.oscargicast.com/"
    GENERIC_TIMEZONE:
      value: "America/Lima"
    TZ:
      value: "America/Lima"
    DB_POSTGRESDB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: n8n-db-credentials
          key: password

  persistence:
    enabled: true
    type: dynamic
    storageClass: local-path
    size: 5Gi

  resources:
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 2Gi
      cpu: 500m
