---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-widget-secrets
  namespace: homelab
spec:
  encryptedData:
    HOMEPAGE_VAR_SPEEDTEST_KEY: AgAQIStrcBURMkzYPsZyGjwKvC5lde5ncn8Ez4I+Wk4GJtUSFC4uRRBVBBSlTOY6Hq7CC4pqat1n0wEORAmYtsy1iKhP+/LimkHjACYSoFc7KLXmiyjX+CdnmvMys6NHD7oVi0gINMBlP9dp93E+3ePs8bvnEAYm10ZGtF0zUxV33lxLRTpIYDblh9X66y2orLOvuyYdtG4/0LlMsK+3J3RVixairr3M8gYT0lvb475t+h2Ac5pqKlmM7nSdGDIoX671BgBLl0T2P+X7px4kFsPcNj12xFUUiiVAqqMq4NckVllq3amZrGVVvCG4hRA/QZJ7KJpb9GmQNTrh2FRiQTw2/suCHWFOZwMtMsk/eH7eDxprLPKUI+Gv3cZf8caXy/x0wO4P6R/OW7Ey9CUBwhWyCN87uHx3KCsBTvGiFGK0cMf4iGDK5AJ+jwomjMLP2LameczpKF2hxwceG79r1FbogQcwHv46DewKE5Mahq6BogHjqHPD5MR/r55eReeKeHPLYczvIFImGd/nqmju90uUSVYer0ol9iHk28zlEXMWIsbOjRgr/OOGkgPRRSoLZuYkWmbTu7fDEOUaJ/SCFaUXnAqWxbhb+iW3fkdPKWBrziRsPx2COVnp3wUnbOZBEu1dIigRyXWnSpyVYjMEuoqdeTimlzQKP7qDu0w4oDBcrvSwOlJB5+Fsnd6a1KnJOOZ7OzRpdFV9wobLjbAydfmx9wmhjcMS9v0Of7nB5CDhKqs2cN3cpnciNdwCcyE9sNU=
  template:
    metadata:
      name: homepage-widget-secrets
      namespace: homelab
    type: Opaque
