apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: infisical-postgres
  namespace: databases
spec:
  instances: 1
  storage:
    size: 5Gi
    storageClass: local-path
  bootstrap:
    initdb:
      database: infisical
      owner: infisical
      secret:
        name: infisical-db-user
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  monitoring:
    enablePodMonitor: true
