apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: evolution-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/oscargicast/homelab-k8s.git
    targetRevision: HEAD
    path: automation/evolution-api
    directory:
      include: "{deployment.yaml,service.yaml,sealed-secret.yaml,ingress-public.yaml,service-monitor.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: automation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
