apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: evolution-api-secrets
  namespace: automation
spec:
  resyncInterval: 60
  authentication:
    kubernetesAuth:
      identityId: eb8dcdde-9d20-49e5-a2ff-28e7598bee36
      serviceAccountRef:
        name: infisical-operator-controller-manager
        namespace: infisical-operator
  projectSlug: homelab-k8s
  envSlug: prod
  secretsPath: /automation/evolution-api
  managedSecretReference:
    secretName: evolution-api-secrets
    secretNamespace: automation
    creationPolicy: Owner
