---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: evolution-api-secrets
  namespace: automation
spec:
  encryptedData:
    api-key: AgAqqHqSPLKrpdGI5O7uhur+ZRuKWj+9FtiKAgie4yJDN13YWB+ofybMqwrTNoRwh6Pzt08Z6LWPYBnj5XqcTRo98Z28q9qoc2DVGNAl3Qo4BuTQpO8FDqGfswsNCt489MBBMEYzLruJh+2IQ0U+o1MnuB934o0oexfCZdaeSkZK8vDekdJeipyjOktLIMF+IVCpJTpFY3zT3BVGdcRPIRE8viFnUvlclsZxDqZxywhsCo42bny2qFUhLgEwkeRKLoBkeSHWbGjWL03ePkjjPDCpDFrKlei23hy16mCbD0oTEUf3J+/yl/1VEuf5oPI+Lrgy5R4QaIZTHkPacReoy72RLHW4aCftsGKkEgRRtd748K4QhyaJrdw2fRWWGiEYqY/dJYR/t2n4q3CQvhZpCStRU0WTwAB4ujge7yZpgqekv6pI1jC+RqowDsLXuGHyXZfapIvEtNczBr0vJZUC4qpuXfpS5MAERgZmtNCrPS631N70BnoyCgIH33CLovJNAx6GGziTLMjTx1k9EXsUYMjo9GQYhY8TRHhLE2nCFVU2HmDBSpKU2rBmt+FphpdLs0bL83EwrH4LHizOiNgHrTwDVD/5St84GaJlHIbhfx4E2eW6mWvnUET6nUqMGRiwzboFlp8tzM03u/bmKpPDEzbIGjBeoebmbY/OyQl72J6Zpf/dgkcEr2Jup/fscwpsemIjALPip2jK2hNMqWYqquTapqSAYVTbg6XnIeqEBgxr4PIx2oWA9bF3d9CjQg==
    database-url: AgAJWilpUISDPWTqNMktr6Lq/JacfigkOMmqJui5vKiWGZqsrEkmyq+VwS9lQz8UL0W5VtKMaSzaxAMcuj28/lYQVZcO5DxKZeOlTLmuqWkFBoL0aiGHN9YZbXQ4drQT63+D3Fo2d4iK5Fn8wqwsuEnVdds4EmcnKujqOUnfuAchSSP/+hW1YbXrMz1QktHJuQM0TPLnLoUC5nv0ga85/nnuDuKg1CjR+BpoPUcPjZrccZd4V6xLQExik/hXswQotA14FRdeKrnUcX4gFGZ9BTraX84lrmED9/sxEuc4kjFla9yTg/4G1XeeqbB0WebJEMqonenN8w0tUfVhXxzJTTcIJzWGQ5ZTgzQdLWlWqJOuXJ+0tAHGLlFIZLMklkVYruzqFpjfP6jEZ8iCqYCV5QB/TBYMoE7Zjek0Zy9FhKmLjhjws0ULJFSSm3uubaAiSAEgX1txL7nIMxuK0byscXEMuN91Cn5aAPIjlH4KNBD15kmK+1RHCZhHpcHVN+QK9PHI4YbvUI0BXNnydLa76xwvI0pFlo1tEtOqGvOpRy8duuCl7g5yOjHXIUv7gICtNiXONG5Zm2VPOmfBrOpV8b8kfrgEn2krw1s+4dackJEq5zCNYRvFPKDsLBnK+/Eve0vOCSryXpWGLRmxUBhj2onwUFhaN/k4s3IT16ZNpmYw9NIkhDE8/lNamdTSRn59zLoBVHEF+DWa2B4oa7RHrGJsjjw/5WuCwyc6Y5ZguiKNIHlbdNG3PlXPz7GJb6ghYmN/Wjhkmuqqu5A62uuXUyz+ufWlVBFBmJdYCkwOA5QOj++fUljO5H18sdfztf9qQHzfvxGkJyixoIdMUG//SxsZ5k/ViPRWhXE=
  template:
    metadata:
      name: evolution-api-secrets
      namespace: automation
    type: Opaque
