apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: evolution-api
  namespace: automation
  labels:
    app.kubernetes.io/name: evolution-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: evolution-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
