---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: evolution-db-user
  namespace: databases
spec:
  encryptedData:
    password: AgC9hLMEQyAQmEHyxI4JMUSSLkur6wtMLNyRb4x0XyG6Qc7JNGKpVUEGhw8jFfjLEuDwL2JwJxPibmkNRKnzihKoANhU5mD21TgTyz+QGhHyL6yzJE93rX+lE3w9sH1kCjdUFPdvQZqjTaRMJELo4ZSdt2EnHWIc8fewOxTtMDOBGiIIukalUqmqIAr2pbrIvDUm7K7xhWZPOKruH1gxGQyLi2SDMjM/psFLSeSD0PFL+VbyFgU6s7mtGEenkGhi58zDikFk0Fqd+5nfMSfeMycyda9W2ZlXPRFhHYT97QM7wB2wZj5B7dLD/DrkvEiJimlED0EQkIkgVCSJmiRq9GkADHkj4kirUdaQxyCSbYtm0QeFCTxT2dlpeWG2R0PKqC/qFDNBn2Hux6S2+Kbj7qS4JrCSIM8pZd3eYuA5vho/y33LRh+uiJd7Oc21aIGOPbTiVtx+EPgq/FOyyf8hbCzxmNVc/9h3vGeIHP592OJAYyqKswVZ+Vj9yIGuOXKsYusvWC0hvmCVrfVRSznjxJYEMQM15/oO/BpT1ESEfXiEcGe6vsL/rao+tO+PAw1DgQsWM5C69z7C0gy3/nBSRoLoPBghjMV3Xk5JKoBsbVJyi2JG9OPD+Z+yLJdJ5VpYH6HeHrXr4ciqCQv+53GaA6KbPWYlp6egjRlIbOtf5txHyGftgf6zLvwxOBjqDlpuKX+QqkljlerEewLtwpMPi+oJiQ++77VT7EyoQ6+Krql7IA==
    username: AgA6pLcTbGqBwZeTGHdZbVIywwXdgaN7MWewmS/Hl0QHY47jIVQiRdb9oP8OOUmVtzIQkd+bpGlxBrOA59uIfq4/PVV+ZTgjzgKXA+4VdWnqUwViaMTEvri6mSyFVYNBfcfLkD5EuKK5huFjcAMHh6SL49r+Oyjk5bddXfJx+piuDCrMkIF2ivf1KNdW6iWD93NLdnHTn48LV+TrExCx6ie2ytA3lI4W5ov12PA0pLcMD3F8gtBptZNYQGRjeRG7l9saeh2/2ae35ZieXw6ZEy0qHjlqDkOt7GFqB877ZbdVXuwnIjPqYO/LTADKyNkFeJCwFyEJ3vkFYRJTABaW0xzT2Ehe9CgPLuQ0jgqBC5onsM5+Ogx5sTxJiiZVP038f2mg/ZV1/5c8MA4k1PZpNqL0hnfCk4BnTXsT4COdPSjaZvb7qDB+KP2rSDBX/bWygy/8x4v1uMxZ7MU7oe1vHVoLEZsiDEFT7mwrvxc0YGDWo/v7mqhYifnrOUY95Aq/VG5cAlbXF3ZK+T+0gw0VxhvsSZnwpTuOR5XdmicsfC9HWQlqkTzuHRi9RpnqfatXdreS3fGEKS+F2vOn4YZzeL2vpS7g9y6YMUshFoXfukreCakZWNemd0+Gm/oAbwjNRVGt0/Mi4MCsXgWq86pI8KP6AvaBsZwvPKnZvHxmEBDhrZ8HP56PiM8ZY3ZqR1KRXE/a8WCsFTO660E=
  template:
    metadata:
      name: evolution-db-user
      namespace: databases
    type: kubernetes.io/basic-auth
